const Enums = {
  app: "app",
  home: "home",
  education: "education",
  experience: "experience",
  projects: "projects",
  certificate: "certificate",
  skills: "skills",
  achievement: "achievement",
  basicDisplay: "basicDisplay",
  bottomBar: "bottomBar",
  headerInfo: "headerInfo",
  htmlComponent: "htmlComponent",
  nav: "nav",
  input: "input",
  nodata_ok: "nodata_ok",
  nodata_404: "nodata_404",
  onelinerHeader: "onelinerHeader",
};
export default Enums;
